# Generated by Django 4.2.7 on 2024-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('translator', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
